return {
	crawl_blastsml = {
		areaofeffect = 280,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.35,
		explosiongenerator = "custom:genericunitexplosion-large-dirty",
		impulseboost = 0,
		impulsefactor = 0,
		name = "WimpyCrawlingBomb",
		range = 400,
		reloadtime = 3.6,
		soundhit = "xplonuk3",
		soundstart = "largegun",
		turret = 1,
		weaponvelocity = 250,
		damage = {
			commanders = 1000,
			crawlingbombs = 400,
			default = 2000,
		},
	},
	crawl_blast = {
		areaofeffect = 400,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.35,
		explosiongenerator = "custom:genericunitexplosion-huge-dirty",
		impulsefactor = 0.3,
		name = "CrawlingBomb",
		range = 450,
		reloadtime = 3.6,
		soundhit = "xplonuk3",
		soundstart = "largegun",
		turret = 1,
		weaponvelocity = 250,
		damage = {
			commanders = 1250,
			crawlingbombs = 400,
			default = 2500,
		},
	},

	crawl_blastsmlscavboss = {
		areaofeffect = 1500,
		craterareaofeffect = 1500,
		craterboost = 0.4,
		cratermult = 0.2,
		edgeeffectiveness = 0.25,
		explosiongenerator = "custom:newnukehuge",
		impulseboost = 0,
		impulsefactor = 0,
		name = "HugeAssMegaNuke",
		range = 400,
		reloadtime = 3.5999999046326,
		soundhit = "xplomed4",
		soundstart = "largegun",
		turret = 1,
		weaponvelocity = 250,
		damage = {
			commanders = 560,
			default = 56000,
		},
	},
	fb_blastsml = {
		areaofeffect = 200,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.34999999403954,
		explosiongenerator = "custom:genericunitexplosion-medium-dirty",
		impulseboost = 0,
		impulsefactor = 0,
		name = "WimpyFlyingBomb",
		range = 400,
		reloadtime = 3.5999999046326,
		soundhit = "xplomed4",
		soundstart = "largegun",
		soundstartvolume = 30,
		turret = 1,
		weaponvelocity = 250,
		damage = {
			commanders = 220,
			default = 440,
		},
	},
}
